#ifndef __CROSS_H__
#define __CROSS_H__
//
// This file was generated by OmicronSoft: CursorGen.
// Modification to this file will be lost the next
// time the cursor(s) are generated.
// If you have any enhancments to the application,
// please contact tegen@inetworld.net.
//
static unsigned char Cross[] = {16,1,7,7,
1,0,1,0,1,0,1,0,1,0,1,0,1,0,255,254,
1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,
3,128,3,128,3,128,3,128,3,128,3,128,255,254,255,254,
255,254,3,128,3,128,3,128,3,128,3,128,3,128,0,0
};

static unsigned char HollowCross[] = {16,1,7,7,
1,0,1,0,1,0,1,0,15,224,8,32,8,32,248,62,
8,32,8,32,15,224,1,0,1,0,1,0,1,0,0,0,
3,128,3,128,3,128,31,240,31,240,24,48,248,62,248,62,
248,62,24,48,31,240,31,240,3,128,3,128,3,128,0,0
};

#endif
